name: Test Automation WorkFlow

on:
  schedule:
  - cron: 00 18 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Running Test Automation framework with Maven
      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=true -DisHeadless=true

    - name: Upload Test logs
      if: always()
      uses: actions/upload-artifact@v6.0.0
      with: 
       name: Test logs
       path: logs/

    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v6.0.0
      with: 
       name: Test Reports
       path: report.html

    - name: Upload Screenshots as artifacts
      if: always()
      uses: actions/upload-artifact@v6.0.0
      with: 
       name: screenshots
       path: screenshots/

    - name: Test Execution Status
      if: always()
      run: echo "Test Execution completed"
      
